# Generated by Django 4.2.30 on 2026-04-23 20:02

import core.utils.uploads
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.utils.uploads.smart_upload_to, verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Contato de Emergência')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Emergência')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verificado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Assistente',
                'verbose_name_plural': 'Assistentes',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
            },
        ),
        migrations.CreateModel(
            name='OnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('purpose', models.CharField(choices=[('onboarding', 'Onboarding'), ('reset_password', 'Reset de Senha'), ('email_change', 'Troca de Email'), ('email_verification', 'Verificação de Email'), ('invitation', 'Convite para Organização'), ('magic_link', 'Login via Magic Link')], max_length=32, verbose_name='Finalidade')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP de quem solicitou a criação do token.', null=True, verbose_name='IP de criação')),
                ('created_ua', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent (criação)')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado em')),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso')),
                ('used_ua', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Dados extras')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_service_at', models.DateTimeField(blank=True, help_text='Preenchido automaticamente no 1º agendamento.', null=True, verbose_name='Primeiro serviço em')),
                ('welcome_email_sent', models.BooleanField(default=False, verbose_name='Email de boas-vindas enviado')),
                ('objective', models.TextField(blank=True, help_text='Ex: emagrecimento, hipertrofia, condicionamento, reabilitação, qualidade de vida.', verbose_name='Objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas da empresa')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Preenchido ao desvincular cliente. Preserva histórico operacional — use ClientService.archive().', null=True, verbose_name='Arquivado em')),
            ],
            options={
                'verbose_name': 'Cliente da Organização',
                'verbose_name_plural': 'Clientes da Organização',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='account.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Membro da Organização',
                'verbose_name_plural': 'Membros da Organização',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('registration_type', models.CharField(blank=True, help_text='Ex: CREF, CRP, CRN, CREFITO', max_length=10, verbose_name='Tipo de Registro')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Nº Registro')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='account.organizationmember', verbose_name='Membro')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='account.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
