# Generated by Django 4.2.30 on 2026-04-23 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.role', verbose_name='Papéis'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Membro da empresa que criou o vínculo (shadow client). Vazio se o cliente se cadastrou sozinho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_links', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='account.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_links', to='account.client', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Sempre preenchido via OnboardingService.register(). Nullable apenas por ordem de criação na transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='onboardingtoken',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas em fluxos vinculados a uma organização (ex: onboarding).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tokens', to='account.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='onboardingtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to='account.organizationmember', verbose_name='Membro'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='account.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_member_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationclient',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'organization'), name='unique_active_client_org'),
        ),
        migrations.AddIndex(
            model_name='onboardingtoken',
            index=models.Index(fields=['user', 'purpose', 'used_at'], name='account_onb_user_id_b91cd1_idx'),
        ),
    ]
