# Generated by Django 4.2.30 on 2026-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtoken',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='onboardingtoken',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP de quem solicitou a criação do token.', null=True, verbose_name='IP de criação'),
        ),
        migrations.AddField(
            model_name='onboardingtoken',
            name='created_ua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent (criação)'),
        ),
        migrations.AddField(
            model_name='onboardingtoken',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas em fluxos vinculados a uma organização (ex: onboarding).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tokens', to='account.organization', verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='onboardingtoken',
            name='purpose',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('reset_password', 'Reset de Senha'), ('email_change', 'Troca de Email'), ('email_verification', 'Verificação de Email'), ('invitation', 'Convite para Organização'), ('magic_link', 'Login via Magic Link')], max_length=32, verbose_name='Finalidade'),
        ),
        migrations.AddIndex(
            model_name='onboardingtoken',
            index=models.Index(fields=['user', 'purpose', 'used_at'], name='account_onb_user_id_b91cd1_idx'),
        ),
    ]
