# Generated by Django 4.2.30 on 2026-04-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingtoken',
            name='purpose',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('reset_password', 'Reset de Senha'), ('email_change', 'Troca de Email'), ('email_verification', 'Verificação de Email'), ('invitation', 'Convite para Organização'), ('magic_link', 'Login via Magic Link'), ('org_activation', 'Ativação de Empresa Adicional')], max_length=32, verbose_name='Finalidade'),
        ),
    ]
