# Generated by Django 4.2.30 on 2026-04-26 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_onboardingtoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='left_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desligamento'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='remuneration_type',
            field=models.CharField(choices=[('fixed', 'Salário Fixo'), ('commission', 'Apenas Comissão'), ('both', 'Fixo + Comissão')], default='fixed', max_length=20, verbose_name='Tipo de Remuneração'),
        ),
    ]
