# Generated by Django 4.2.30 on 2026-04-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='account.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Módulo da Organização',
                'verbose_name_plural': 'Módulos da Organização',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationmodule',
            constraint=models.UniqueConstraint(fields=('organization', 'module'), name='unique_organization_module'),
        ),
    ]
