# Generated by Django 4.2.30 on 2026-04-20 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_core', models.BooleanField(default=False, help_text='Módulos core são ativados automaticamente em toda organização nova.', verbose_name='módulo essencial')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='exibir no menu')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('url_name', models.CharField(blank=True, default='', max_length=150, verbose_name='nome da rota')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='exibir no menu')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.module', verbose_name='módulo')),
            ],
            options={
                'verbose_name': 'item do módulo',
                'verbose_name_plural': 'itens do módulo',
                'ordering': ['module__order', 'module__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('action', models.CharField(choices=[('view', 'Visualizar'), ('add', 'Adicionar'), ('change', 'Alterar'), ('delete', 'Excluir')], max_length=20, verbose_name='ação')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('codename', models.CharField(blank=True, max_length=150, unique=True, verbose_name='codename')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.moduleitem', verbose_name='item do módulo')),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'ordering': ['item__module__order', 'item__order', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='nível')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='account.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('effect', models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Negar')], default='allow', max_length=10, verbose_name='Efeito')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='account.organization', verbose_name='Organização')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='core.permission', verbose_name='Permissão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão do Usuário',
                'verbose_name_plural': 'Permissões do Usuário',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='account.organization', verbose_name='Organização')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='core.permission', verbose_name='Permissão')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role', verbose_name='Papel')),
            ],
            options={
                'verbose_name': 'Permissão do Papel',
                'verbose_name_plural': 'Permissões do Papel',
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_modules', to='core.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_modules', to='account.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Módulo da Organização',
                'verbose_name_plural': 'Módulos da Organização',
            },
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'permission'), name='unique_user_permission_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('organization', 'role', 'permission'), name='unique_role_permission_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_role_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_role_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('item', 'action'), name='unique_permission_item_action'),
        ),
        migrations.AddConstraint(
            model_name='organizationmodule',
            constraint=models.UniqueConstraint(fields=('organization', 'module'), name='unique_organization_module'),
        ),
        migrations.AddConstraint(
            model_name='moduleitem',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_module_item_name'),
        ),
        migrations.AddConstraint(
            model_name='moduleitem',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='unique_module_item_slug'),
        ),
    ]
