# Generated by Django 4.2.30 on 2026-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(choices=[('account', 'Configurações'), ('settings', 'Cadastros'), ('my-area', 'Minha Área'), ('saas-admin', 'Admin SaaS')], max_length=120, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='moduleitem',
            name='slug',
            field=models.SlugField(choices=[('role', 'Papel'), ('member', 'Membro'), ('organization', 'Organização'), ('client', 'Cliente'), ('collaborator', 'Colaborador'), ('dashboard', 'Dashboard'), ('profile', 'Perfil'), ('organizations', 'Organizações (Admin)')], max_length=120, verbose_name='slug'),
        ),
    ]
