# Generated by Django 4.2.30 on 2026-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='scope',
            field=models.CharField(choices=[('superuser', 'Admin SaaS'), ('global', 'Global (Cliente)'), ('tenant', 'Organização')], default='tenant', help_text='Define em qual contexto o módulo aparece: área admin (superuser), área do cliente (global) ou dentro de uma organização (tenant).', max_length=20, verbose_name='escopo'),
        ),
        migrations.AlterField(
            model_name='moduleitem',
            name='slug',
            field=models.SlugField(choices=[('client', 'Cliente'), ('role', 'Papel'), ('member', 'Membro'), ('organization', 'Organização'), ('dashboard', 'Dashboard'), ('profile', 'Perfil'), ('organizations', 'Organizações (Admin)'), ('users-admin', 'Usuários (Admin)'), ('dashboard-admin', 'Painel Admin'), ('specialty', 'Especialidades')], max_length=120, verbose_name='slug'),
        ),
    ]
