# Generated by Django 4.2.30 on 2026-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleitem',
            name='slug',
            field=models.SlugField(choices=[('client', 'Cliente'), ('role', 'Papel'), ('member', 'Membro'), ('organization', 'Organização'), ('dashboard', 'Dashboard'), ('profile', 'Perfil'), ('organizations', 'Organizações (Admin)')], max_length=120, verbose_name='slug'),
        ),
    ]
