# Generated by Django 4.2.30 on 2026-04-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleitem',
            name='url_name',
        ),
    ]
