# Generated by Django 4.2.30 on 2026-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleitem',
            name='route',
            field=models.CharField(blank=True, default='', help_text="Ex: 'settings:client_list' ou 'personal:billing'. Se vazio, cai no fallback derivado do slug.", max_length=120, verbose_name='rota (URL name)'),
        ),
    ]
