# Generated by Django 4.2.30 on 2026-04-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_module_slug_alter_moduleitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleitem',
            name='route',
            field=models.CharField(blank=True, default='', help_text="Ex: 'settings:client_list' ou 'master:billing'. Se vazio, cai no fallback derivado do slug.", max_length=120, verbose_name='rota (URL name)'),
        ),
        migrations.AlterField(
            model_name='moduleitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Módulo que controla a disponibilidade do item para a organização. Se vazio, o próprio 'module' controla.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='core.module', verbose_name='módulo controlador'),
        ),
    ]
