# Generated by Django 4.2.28 on 2026-04-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_moduleitem_url_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moduleitem',
            name='unique_module_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='moduleitem',
            name='unique_module_item_slug',
        ),
    ]
